config/routes.rb
Rails.application.routes.draw do
  root 'sessions#unauth'

  get 'sessions/unauth', as: :login
  post 'sessions/login', as: :signin
  delete 'sessions/logout', as: :logout

  resources :users, only: [:create, :new, :update, :edit]
  delete '/users/:id', to: 'users#destroy', as: 'delete_user'
  resources :articles, only: [:index, :show]
  get '/admin/scrape', to: 'admins#scrape', as: 'scrape'
  get '/admin/email', to: 'admins#email', as: 'email'
  get '/interests', to: 'articles#my_interests', as: 'interests'
  get '/email', to: 'articles#email_service', as: 'email_service'
  get '/search', to: 'articles#search', as: 'search'

end

app/models/user.rb
# Model for user, a corresponding table is build in database
class User < ActiveRecord::Base
  # Validations
  validates_presence_of :email, :first_name, :last_name, :username, :password, :password_confirmation
  validates_uniqueness_of :username
  validates :email, format: { with: /(.+)@(.+).[a-z]{2,4}/, message: '%{value} is not a valid email' }
  validates :first_name, format: { with: /[A-Za-z]+/, message: '%{value} is not alphabetic' }
  validates :username, length: { minimum: 3, too_short: '%{count} characters is the minimum allowed' }
  validates :password, length: { minimum: 8, too_short: '%{count} characters is the minimum allowed' }
  attr_readonly :username

  # Users can have interests
  acts_as_taggable_on :interests

  # Use secure passwords
  has_secure_password
  has_many :comments

  # Find a user by email, then check the username is the same
  def self.authenticate(username, password)
    user = User.find_by(username: username)
    if user && user.authenticate(password)
      return user
    else
      return nil
    end
  end

  def full_name
    first_name + ' ' + last_name
  end
end

app/controllers/users_controller.rb
# Controller for user
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:edit, :destroy, :update]
  before_action :check_valid, only: [:edit, :destroy, :update]

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # user /users
  # user /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to articles_path, notice: 'user was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to articles_path, notice: 'user was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    log_out
    @user.destroy
    respond_to do |format|
      format.html { redirect_to login_path, notice: 'user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def check_valid
      unless @user == current_user
        render file: 'public/403.html', status: 403, layout: false
      end
    end

    # Only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :bio, :username, :password, :interest_list, :password_confirmation, :email_service)
    end
end

app/views/users/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading"> Create A New User </div>
  <div class="panel-body">

    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <h3> Tell us who you are! </h3>
      <div class="form-group">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>

      <h3> Pick a username and password! </h3>
      <div class="form-group">
        <%= f.label :username %><br>
        <% if !current_user %>
          <%= f.text_field :username, class: 'form-control' %>
        <% else %>
          <%= f.text_field :username, :readonly=>true, class: 'form-control' %>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :password %><br>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
  

      <h3> Nearly There! </h3>
      <div class="form-group">
        <%= f.label :email %><br>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :bio %><br>
        <%= f.text_field :bio, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :interest_list %><br>
        <%= f.text_field :interest_list, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email_service %><br>
        <%= f.check_box :email_service, class: 'form-control' %>
      </div>      

      <div class="form-group">
        <%= f.submit 'Save', class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<div class="btn-group  pull-right" role="group">
  <%= link_to 'Delete Account', delete_user_path(current_user), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default" %>
</div>
<br />
<br />
<br />

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>