config/routes.rb
Rails.application.routes.draw do
  root 'sessions#unauth'

  get 'sessions/unauth', as: :login
  post 'sessions/login', as: :signin
  delete 'sessions/logout', as: :logout

  resources :users, only: [:create, :new, :update, :edit]
  delete '/users/:id', to: 'users#destroy', as: 'delete_user'
  resources :articles, only: [:index, :show]
  get '/admin/scrape', to: 'admins#scrape', as: 'scrape'
  get '/admin/email', to: 'admins#email', as: 'email'
  get '/interests', to: 'articles#my_interests', as: 'interests'
  get '/email', to: 'articles#email_service', as: 'email_service'
  get '/search', to: 'articles#search', as: 'search'

end

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">TheDigest</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Articles", articles_path %></li>
          <li><%= link_to "Interests", interests_path %></li>
          <%if current_user.email_service%>
            <li><%= link_to "Email Service", email_service_path %></li>
          <% end %>          
        </ul>
        <form class="navbar-form navbar-right" role="search" action="/search">
            <div class="form-group">
            <input type="text" class="form-control" name="search" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to current_user.full_name, edit_user_path(current_user)%></li>
          <li><%= link_to "Log Out", logout_path, method: :delete%></li>
        </ul>
      <% end %> 

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheDigest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: '/layouts/nav_bar' %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>